# Generated by Django 5.2.7 on 2025-11-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='translated_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
