from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView
from apps.users.views import MyTokenObtainPairView

from apps.films.views import FilmViewSet
# Import the new view along with the ViewSet
from apps.comments.views import CommentViewSet, FilmCommentListView # <-- UPDATE THIS IMPORT
from apps.thumbs.views import ThumbViewSet

# Router for standard CRUD endpoints
router = DefaultRouter()
router.register(r'films', FilmViewSet, basename='film')
router.register(r'comments', CommentViewSet, basename='comment') # Handles POST comments
router.register(r'thumbs', ThumbViewSet, basename='thumb')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/users/', include('apps.users.urls')),
    path('api/token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    # --- ADD THIS NEW URL PATTERN ---
    # Example: /api/films/1/comments/ will call FilmCommentListView
    path('api/films/<int:film_pk>/comments/', FilmCommentListView.as_view(), name='film-comments-list'),
    # --- END OF NEW URL PATTERN ---

    # Include URLs generated by the router (covers /api/films/, /api/comments/, etc.)
    path('api/', include(router.urls)),
]